spark:
   car_sql: "
    select a.platenum,a.idcard,b.dev_chnid,b.dev_id,b.cap_date captime,a.person_type,
    from_unixtime(unix_timestamp(),'yyyy-MM-dd HH:mm:ss') create_date  
    from 
    (
     select car.platenum,car.idcard,kp.id,pt.person_type 
     from bs_list.key_person_car car 
     left join bs_list.key_person kp
     on car.idcard=kp.idcard
     left join bs_list.rel_key_person_type pt
     on kp.id=pt.person_id       
    ) a
    inner join
    (
     select car_num,dev_chnid,dev_id,car_direct,cap_date
     from dssc.c_picrecord_src 
     where length(car_num)>=5 and cap_date >= from_unixtime(unix_timestamp()-24*60*60)
    ) b
    on a.platenum=b.car_num"
   sql: "select person_id,person_type from tmp.rel_key_person_type"


mysql:
   user: root
   password: bfd123456
   url: jdbc:mysql://10.236.54.237:3306/bs_list?characterEncoding=UTF-8&useSSL=False
   bs_list_url: mysql+mysqldb://root:bfd123456@10.236.54.237:3306/bs_list?charset=utf8
 
   t_key_person_total_sql: "(select distinct idcard from key_person ) tmp"
   t_key_person_car_sql: "(select distinct platenum from key_person_car) tmp"
   t_key_person_imsi_sql: "(select distinct imsi from key_person_phone) tmp"
   t_key_person_mac_sql: "(select distinct mac from key_person_phone) tmp"
   t_car_type_num_sql: ""
   t_person_type_number_sql: "(select person_type from rel_key_person_type) tmp"
   t_department_key_person_sql: ""
   

redis:
   host: 10.152.199.108
   port: 6379
   pass: redis2017
